baseURL = "https://megan.ieuanjenkins.com/"
languageCode = "en-gb"
title = "Megan Whiting"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-20427637-2"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  favicon = ""
  description = "Megan Whiting"
  facebook = "https://www.facebook.com/meganwhitingfreelance"
  twitter = "https://twitter.com/meganrose8"
  instagram = "https://www.instagram.com/megsss90/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/megan-whiting-freelance/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-F4F4F4"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
